export const APPLY_PROMO_CODE = 'APPLY_PROMO_CODE';
export const UPDATE_CART_SUB_TOTAL = 'UPDATE_CART_SUB_TOTAL';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';
export const UPDATE_CART_ITEM_COLOR = 'UPDATE_CART_ITEM_COLOR';
export const UPDATE_CART_ITEM_SIZE = 'UPDATE_CART_ITEM_SIZE';

export const raw = [
   {
      "p_id":"1",
      "p_image":"https://media.gucci.com/style/DarkGray_South_0_160_316x316/1530210606/492347_X3P69_4725_001_100_0000_Light-Oversize-GucciHallucination-T-shirt.jpg",
      "p_name":"Cotton Tshirt",
      "p_variation":"solid green",
      "p_style":"ms13kt1906",
      "p_selected_color":{
         "name":"blue",
         "hexcode":"#1169BD"
      },
      "p_selected_size":{
         "name":"small",
         "code":"s"
      },
      "p_available_options":{
         "colors":[
            {
               "name":"green",
               "hexcode":"#A3D2A1"
            },
            {
               "name":"yellow",
               "hexcode":"#F9F8E6"
            },
            {
               "name":"blue",
               "hexcode":"#1169BD"
            }
         ],
         "sizes":[
            {
               "name":"small",
               "code":"s"
            },
            {
               "name":"medium",
               "code":"m"
            },
            {
               "name":"large",
               "code":"l"
            },
            {
               "name":"extra large",
               "code":"xl"
            }
         ]
      },
      "p_quantity":1,
      "p_originalprice":11,
      "p_price":11,
      "c_currency":"$"
   },
   {
      "p_id":"2",
      "p_name":"Print Girls Tee",
      "p_image":"https://media.gucci.com/style/DarkGray_South_0_160_316x316/1530210606/492347_X3P69_4725_001_100_0000_Light-Oversize-GucciHallucination-T-shirt.jpg",
      "p_variation":"pink rainbow",
      "p_style":"ms13kt1906",
      "p_selected_color":{
         "name":"pink",
         "hexcode":"#F1DDEF"
      },
      "p_selected_size":{
         "name":"small",
         "code":"s"
      },
      "p_available_options":{
         "colors":[
            {
               "name":"green",
               "hexcode":"#A3D2A1"
            },
            {
               "name":"yellow",
               "hexcode":"#F9F8E6"
            },
            {
               "name":"pink",
               "hexcode":"#F1DDEF"
            }
         ],
         "sizes":[
            {
               "name":"small",
               "code":"s"
            },
            {
               "name":"medium",
               "code":"m"
            },
            {
               "name":"large",
               "code":"l"
            },
            {
               "name":"extra large",
               "code":"xl"
            }
         ]
      },
      "p_quantity":1,
      "p_originalprice":17,
      "p_price":17,
      "c_currency":"$"
   },
   {
      "p_id":"3",
      "p_name":"Flower Pattern Shirt",
      "p_image":"https://media.gucci.com/style/DarkGray_South_0_160_316x316/1530210606/492347_X3P69_4725_001_100_0000_Light-Oversize-GucciHallucination-T-shirt.jpg",
      "p_variation":"blue",
      "p_style":"ms13kt1906",
      "p_selected_color":{
         "name":"blue",
         "hexcode":"#1169BD"
      },
      "p_selected_size":{
         "name":"small",
         "code":"s"
      },
      "p_available_options":{
         "colors":[
            {
               "name":"green",
               "hexcode":"#A3D2A1"
            },
            {
               "name":"blue",
               "hexcode":"#1169BD"
            },
            {
               "name":"red",
               "hexcode":"#ED99A8"
            }
         ],
         "sizes":[
            {
               "name":"small",
               "code":"s"
            },
            {
               "name":"medium",
               "code":"m"
            },
            {
               "name":"large",
               "code":"l"
            },
            {
               "name":"extra large",
               "code":"xl"
            }
         ]
      },
      "p_quantity":1,
      "p_originalprice":21,
      "p_price":9,
      "c_currency":"$"
   },
   {
      "p_id":"4",
      "p_name":"Check Pattern Tshirt",
      "p_image":"https://media.gucci.com/style/DarkGray_South_0_160_316x316/1530210606/492347_X3P69_4725_001_100_0000_Light-Oversize-GucciHallucination-T-shirt.jpg",
      "p_variation":"mens red",
      "p_style":"ms13kt1906",
      "p_selected_color":{
         "name":"red",
         "hexcode":""
      },
      "p_selected_size":{
         "name":"medium",
         "code":"m"
      },
      "p_available_options":{
         "colors":[
            {
               "name":"green",
               "hexcode":"#A3D2A1"
            },
            {
               "name":"yellow",
               "hexcode":"#F9F8E6"
            },
            {
               "name":"red",
               "hexcode":"#ED99A8"
            }
         ],
         "sizes":[
            {
               "name":"small",
               "code":"s"
            },
            {
               "name":"medium",
               "code":"m"
            },
            {
               "name":"large",
               "code":"l"
            },
            {
               "name":"extra large",
               "code":"xl"
            }
         ]
      },
      "p_quantity":1,
      "p_originalprice":22,
      "p_price":22,
      "c_currency":"$"
   }
]
